/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.customerservice.deep;import jakarta.persistence.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="cs_customers",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","customerCode"})) class Customer{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;String organizationCode,customerCode,name,level,contactName,contactPhone;boolean active=true;LocalDateTime createdAt=LocalDateTime.now();/**
                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                               */
protected Customer(){}/**
                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                     */
Customer(String o,String c,String n,String l,String contact,String phone){organizationCode=o;customerCode=c;name=n;level=l;contactName=contact;contactPhone=phone;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="cs_tickets",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","ticketNo"})) class ServiceTicket{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;String organizationCode,ticketNo;Long customerId;String channel,category,priority,subject,description,status="NEW",assignee,resolution;LocalDateTime createdAt=LocalDateTime.now(),dueAt,firstResponseAt,resolvedAt,closedAt,updatedAt=LocalDateTime.now();int reopenCount;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
protected ServiceTicket(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
ServiceTicket(String o,String n,Long c,String channel,String category,String p,String subject,String d,int sla){organizationCode=o;ticketNo=n;customerId=c;this.channel=channel;this.category=category;priority=p;this.subject=subject;description=d;dueAt=createdAt.plusMinutes(sla);}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="cs_ticket_messages") class TicketMessage{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;Long ticketId;String messageType,senderName;@Column(length=2000)String content;LocalDateTime sentAt=LocalDateTime.now();/**
                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                    */
protected TicketMessage(){}/**
                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                               */
TicketMessage(Long t,String type,String sender,String content){ticketId=t;messageType=type;senderName=sender;this.content=content;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="cs_knowledge_articles",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","articleNo"})) class KnowledgeArticle{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;String organizationCode,articleNo,title,category,status="DRAFT",owner;@Column(length=5000)String content;int helpfulCount;LocalDateTime createdAt=LocalDateTime.now(),publishedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                            */
protected KnowledgeArticle(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
KnowledgeArticle(String o,String no,String title,String c,String content,String owner){organizationCode=o;articleNo=no;this.title=title;category=c;this.content=content;this.owner=owner;}}
