/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.customerservice;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.Pattern;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest @AutoConfigureMockMvc class DeepCustomerServiceTests{@Autowired MockMvc mvc;
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void ticketAssignmentCommunicationResolutionCloseAndReopenWork()throws Exception{long customer=customer("UT-CUST-01"),ticket=ticket("UT-CS-01",customer,240);mvc.perform(post("/api/service/tickets/{id}/assign",ticket).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"assignee\":\"客服小组A\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("ASSIGNED"));mvc.perform(post("/api/service/tickets/{id}/messages",ticket).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"messageType\":\"PUBLIC\",\"senderName\":\"客服专员\",\"content\":\"已完成远程处理，请确认\"}")).andExpect(status().isOk());mvc.perform(post("/api/service/tickets/{id}/resolve",ticket).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"resolution\":\"重新配置客户端参数\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("RESOLVED"));mvc.perform(post("/api/service/tickets/{id}/close",ticket).with(httpBasic("operator","operator123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("CLOSED"));mvc.perform(post("/api/service/tickets/{id}/reopen",ticket).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"问题再次出现\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("REOPENED"));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void resolveRequiresCustomerVisibleReplyAndSlaEscalates()throws Exception{long customer=customer("UT-CUST-02"),ticket=ticket("UT-CS-02",customer,1);mvc.perform(post("/api/service/tickets/{id}/assign",ticket).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"assignee\":\"客服小组B\"}")).andExpect(status().isOk());mvc.perform(post("/api/service/tickets/{id}/resolve",ticket).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"resolution\":\"无客户沟通\"}")).andExpect(status().isConflict());mvc.perform(post("/api/service/sla/escalate").param("organizationCode","UT-CS").param("asOf","2027-01-01T00:00:00").with(httpBasic("operator","operator123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.escalated").value(org.hamcrest.Matchers.greaterThanOrEqualTo(1)));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void knowledgeRequiresAdminPublication()throws Exception{long id=idOf(mvc.perform(post("/api/service/knowledge").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"organizationCode\":\"UT-CS\",\"articleNo\":\"KA-UT-01\",\"title\":\"客户端连接排查\",\"category\":\"连接问题\",\"content\":\"检查网络、证书和代理配置\",\"owner\":\"知识经理\"}")).andExpect(status().isOk()).andReturn());mvc.perform(post("/api/service/knowledge/{id}/submit",id).with(httpBasic("operator","operator123"))).andExpect(status().isOk());mvc.perform(post("/api/admin/service/knowledge/{id}/publish",id).with(httpBasic("operator","operator123"))).andExpect(status().isForbidden());mvc.perform(post("/api/admin/service/knowledge/{id}/publish",id).with(httpBasic("admin","admin123"))).andExpect(status().isOk());mvc.perform(get("/api/service/knowledge/search").param("organizationCode","UT-CS").param("keyword","连接").with(httpBasic("operator","operator123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(1));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private long customer(String code)throws Exception{return idOf(mvc.perform(post("/api/service/customers").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"organizationCode\":\"UT-CS\",\"customerCode\":\""+code+"\",\"name\":\"测试客户\",\"level\":\"A\",\"contactName\":\"张经理\",\"contactPhone\":\"13800000000\"}")).andExpect(status().isOk()).andReturn());}/**
                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                             */
private long ticket(String no,long customer,int sla)throws Exception{return idOf(mvc.perform(post("/api/service/tickets").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"organizationCode\":\"UT-CS\",\"ticketNo\":\""+no+"\",\"customerId\":"+customer+",\"channel\":\"WECHAT\",\"category\":\"技术支持\",\"priority\":\"P2\",\"subject\":\"无法连接服务\",\"description\":\"客户端连接失败\",\"slaMinutes\":"+sla+"}")).andExpect(status().isOk()).andReturn());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
private long idOf(MvcResult r)throws Exception{var m=Pattern.compile("\"id\":(\\d+)").matcher(r.getResponse().getContentAsString());Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}}
